development: &common
  adapter: sqlite3
  database: saltscraper
staging:
  <<: *common
  database: saltscraper_staging
production:
  <<: *common
  database: saltscraper_production
test: &test
  <<: *common
  database: saltscraper_test
